PREFIX vcfc: <https://w3id.org/vcf-core/vocab#>

SELECT
  (COUNT(DISTINCT ?sampleCall) AS ?sampleCallCount)
  (COUNT(DISTINCT ?sampleId) AS ?sampleIdCount)
  (COUNT(DISTINCT ?gtValueNode) AS ?gtValueNodeCount)
WHERE {
  OPTIONAL {
    ?sampleCall a vcfc:SampleCall ; vcfc:sampleId ?sampleId .
    OPTIONAL {
      ?sampleCall vcfc:hasFormatValue ?gtValueNode .
      FILTER(STRENDS(STR(?gtValueNode), "/fmt/GT"))
      ?gtValueNode vcfc:fieldValue ?gtLiteral .
    }
  }
}
