PREFIX vcfc: <https://w3id.org/vcf-core/vocab#>

SELECT ?record
       (COUNT(DISTINCT ?chrom) AS ?chromCount)
       (COUNT(DISTINCT ?pos) AS ?posCount)
       (COUNT(DISTINCT ?ref) AS ?refCount)
       (COUNT(DISTINCT ?alt) AS ?altCount)
       (COUNT(DISTINCT ?call) AS ?callCount)
WHERE {
  ?record a vcfc:VCFRecord .
  OPTIONAL { ?record vcfc:chrom ?chrom }
  OPTIONAL { ?record vcfc:pos ?pos }
  OPTIONAL { ?record vcfc:ref ?ref }
  OPTIONAL { ?record vcfc:alt ?alt }
  OPTIONAL { ?record vcfc:hasCall ?call }
}
GROUP BY ?record
HAVING(COUNT(DISTINCT ?chrom) != 1 || COUNT(DISTINCT ?pos) != 1 || COUNT(DISTINCT ?ref) != 1 || COUNT(DISTINCT ?alt) != 1 || COUNT(DISTINCT ?call) != 1)
LIMIT 100
