PREFIX vcfc: <https://w3id.org/vcf-core/vocab#>

SELECT ?file ?profile
WHERE {
  ?file a vcfc:VCFFile .
  OPTIONAL { ?file vcfc:representationProfile ?profile }
  FILTER(!BOUND(?profile) || ?profile != vcfc:CondensedRepresentation)
}
LIMIT 100
