PREFIX vcfr: <https://w3id.org/vcf-rdfizer/vocab#>

SELECT ?file ?profile
WHERE {
  ?file a vcfr:VCFFile .
  OPTIONAL { ?file vcfr:representationProfile ?profile }
  FILTER(!BOUND(?profile) || ?profile != vcfr:CondensedRepresentation)
}
LIMIT 100
