PREFIX vcfc: <https://w3id.org/vcf-core/vocab#>

SELECT
  (COUNT(DISTINCT ?sample) AS ?sampleCount)
  (COUNT(DISTINCT ?sampleId) AS ?sampleIdCount)
  (COUNT(DISTINCT ?gtVector) AS ?gtVectorCount)
WHERE {
  OPTIONAL {
    ?sampleSet a vcfc:SampleSet ; vcfc:hasSample ?sample .
    ?sample vcfc:sampleName ?sampleId .
  }
  OPTIONAL {
    ?gtVector a vcfc:FormatValueVector ; vcfc:declaredBy ?definition ; vcfc:encodedValues ?encoded .
    ?definition vcfc:fieldId "GT" .
  }
}
